### ISSUE TITLE
Replacing a bed in the same spot makes /bed work again.

### ISSUE THREAD

**Issue by stapleshotz** [minecast/bedhome#3]
I made the same ticket using your "BUG REPORTS" link but I noticed it was different from the "tickets" link, and the other one didn't have any past activity so I figured I'd make one here, just in case.

BedHome V 2.26
Bukkit version: git-Bukkit-f631379 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

I've set the nobedmode to "b" in the config, and that works fine. When a bed is set and broken, the player is unable to teleport there. However, if you place a bed on the exact spot afterwards, the player is able to teleport there again.

Is there a way to delete the player's home if the bed is broken?

**Comment by HeroCC** [comment]
Fixed in https://github.com/HeroCC/BedHome/issues/1
